[package]
name = "windmill-trigger-postgres"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_trigger_postgres"
path = "src/lib.rs"

[features]
default = []
enterprise = ["windmill-common/enterprise", "windmill-store/enterprise", "windmill-trigger/enterprise"]
private = ["windmill-common/private", "windmill-store/private"]

[dependencies]
windmill-common = { workspace = true, default-features = false }
windmill-api-auth.workspace = true
windmill-store = { workspace = true, features = ["postgres_trigger"] }
anyhow.workspace = true
windmill-trigger.workspace = true
windmill-git-sync.workspace = true
rust-postgres.workspace = true
rust-postgres-native-tls.workspace = true
pg_escape.workspace = true
native-tls.workspace = true
rust_decimal.workspace = true
byteorder.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
async-trait.workspace = true
itertools.workspace = true
chrono.workspace = true
rand.workspace = true
uuid.workspace = true
bytes.workspace = true
futures.workspace = true
thiserror.workspace = true
quick_cache.workspace = true
lazy_static.workspace = true
