[package]
name = "windmill-test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_test_utils"
path = "src/lib.rs"

[features]
default = []
private = []
enterprise = []
python = ["windmill-common/python"]
deno_core = ["dep:windmill-runtime-nativets"]
agent_worker_server = ["dep:windmill-api-agent-workers"]

[dependencies]
windmill-api = { workspace = true, default-features = false }
windmill-worker.workspace = true
windmill-queue.workspace = true
windmill-common = { workspace = true, default-features = false }
windmill-api-client.workspace = true
windmill-runtime-nativets = { workspace = true, optional = true }
windmill-api-agent-workers = { workspace = true, optional = true }

sqlx.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
chrono.workspace = true
axum.workspace = true
anyhow.workspace = true
tracing.workspace = true
