[package]
name = "windmill-parser-go"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "windmill_parser_go"
path = "./src/lib.rs"

[dependencies]
windmill-parser.workspace = true
windmill-common.workspace = true
phf.workspace = true
unicode-general-category.workspace = true
itertools.workspace = true
anyhow.workspace = true
gosyn.workspace = true