[package]
name = "windmill-operator"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_operator"
path = "./src/lib.rs"

[features]
enterprise = ["windmill-common/enterprise"]
private = []
default = []

[dependencies]
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
windmill-common = { workspace = true, default-features = false, features = ["instance_config_schema"] }
anyhow.workspace = true
thiserror.workspace = true
kube.workspace = true
k8s-openapi.workspace = true
tokio.workspace = true
futures.workspace = true
chrono.workspace = true
schemars = "0.8"
serde_yml.workspace = true
