[package]
name = "windmill-native-triggers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_native_triggers"
path = "src/lib.rs"

[features]
default = []
enterprise = ["windmill-common/enterprise"]
cloud = ["windmill-common/cloud"]
native_trigger = ["dep:windmill-oauth", "dep:backon"]

[dependencies]
windmill-api-auth.workspace = true
windmill-common = { workspace = true, default-features = false }
windmill-audit.workspace = true
windmill-queue.workspace = true
windmill-oauth = { workspace = true, optional = true }
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
http.workspace = true
tracing.workspace = true
tokio.workspace = true
async-trait.workspace = true
lazy_static.workspace = true
reqwest.workspace = true
chrono.workspace = true
itertools.workspace = true
anyhow.workspace = true
base64.workspace = true
hmac.workspace = true
sha2.workspace = true
urlencoding.workspace = true
uuid.workspace = true
strum.workspace = true
backon = { workspace = true, optional = true }
