[package]
name = "windmill-trigger-websocket"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_trigger_websocket"
path = "src/lib.rs"

[features]
default = []
enterprise = ["windmill-common/enterprise", "windmill-trigger/enterprise"]
private = ["windmill-common/private"]

[dependencies]
windmill-common = { workspace = true, default-features = false }
windmill-api-auth.workspace = true
windmill-trigger.workspace = true
windmill-git-sync.workspace = true
windmill-queue.workspace = true
tokio-tungstenite.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
async-trait.workspace = true
itertools.workspace = true
anyhow.workspace = true
futures.workspace = true
http.workspace = true
