[package]
name = "windmill-trigger-email"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_trigger_email"
path = "src/lib.rs"

[features]
default = []
enterprise = ["windmill-common/enterprise", "windmill-trigger/enterprise"]
private = ["windmill-common/private"]

[dependencies]
windmill-common = { workspace = true, default-features = false }
windmill-api-auth.workspace = true
windmill-trigger.workspace = true
windmill-git-sync.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
async-trait.workspace = true
anyhow.workspace = true
base64.workspace = true
regex.workspace = true
lazy_static.workspace = true
