[package]
name = "windmill-trigger-nats"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_trigger_nats"
path = "src/lib.rs"

[features]
default = []
enterprise = ["windmill-common/enterprise", "windmill-store/enterprise", "windmill-trigger/enterprise"]
private = ["windmill-common/private", "windmill-store/private"]

[dependencies]
windmill-common = { workspace = true, default-features = false }
windmill-api-auth.workspace = true
windmill-store = { workspace = true, features = ["nats"] }
windmill-trigger.workspace = true
windmill-git-sync.workspace = true
async-nats.workspace = true
nkeys.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
async-trait.workspace = true
itertools.workspace = true
anyhow.workspace = true
base64.workspace = true
