[package]
name = "windmill-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "windmill_parser"
path = "./src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
convert_case.workspace = true
lazy_static.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
regex-lite.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
regex.workspace = true