[package]
name = "windmill-git-sync"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_git_sync"
path = "./src/lib.rs"

[features]
private = []
enterprise = ["windmill-queue/enterprise", "windmill-common/enterprise"]
all_sqlx_features = ["enterprise"]
default = []

[dependencies]
uuid.workspace = true
serde.workspace = true
sqlx.workspace = true
serde_json.workspace = true
tracing.workspace = true
windmill-common = { workspace = true, default-features = false }
windmill-queue.workspace = true
regex = "1.10.3"
tokio = { workspace = true, features = ["full"] }