name: Change versions
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "version.txt"
jobs:
  change_version:
    runs-on: ubuntu-latest
    container: docker pull fnndsc/python-poetry
    steps:
      - uses: actions/checkout@v3
      - name: Change versions
        run: ./.github/change-versions.sh "$(cat version.txt)"
      - uses: stefanzweifel/git-auto-commit-action@v4
