name: Publish deno-client
on:
  push:
    tags:
      - "v*"
env:
  repo: windmill-deno-client

jobs:
  build_deno_and_push_to_repo:
    runs-on: ubicloud
    steps:
      - uses: actions/checkout@v3
      - name: generate_deno
        run: |
          cd deno-client
          rm .gitignore
          ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@devel
        env:
          API_TOKEN_GITHUB: ${{ secrets.DENO_PAT }}
        with:
          source-directory: deno-client/
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: ${{ env.repo }}
          user-email: ruben@windmill.dev
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main

  tag_repo:
    needs: [build_deno_and_push_to_repo]
    runs-on: ubicloud
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ env.repo }}
          token: ${{ secrets.DENO_PAT }}
          path: ./client

      - name: Push client
        run: |
          cd ./client
          git config --global user.email "ruben@windmill.dev"
          git config --global user.name "rubenfiszel[bot]"
          git tag -a ${{ github.ref_name }} -m "${{ github.ref_name }}"
          git push --tags
