on:
  push:
    branches: [main]

name: release-please
jobs:
  release-please:
    name: "Release please"
    runs-on: ubicloud
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: simple
          package-name: windmill
          release-as: 1.635.0
          token: ${{ secrets.PAT_TOKEN }}
